// 由 serverSettings/parts/*.tsx 与 lib/config/read/{db,env}.ts 推导而来：
// 环境变量覆盖列表原先直接渲染数据库列名（coreTrustProxy 这类），对用户没有意义，
// 这里把它映射成所属分区 + 表单字段标签（复用各分区已有的 i18n key，无需新增译文），
// 并保留真实的环境变量名以便用户知道该改哪个变量。
export const SETTING_META: Record<string, { section: string; label: string; env: string }> = {
  chunksEnabled: { section: 'chunks', label: 'Enable Chunks', env: 'CHUNKS_ENABLED' },
  chunksMax: { section: 'chunks', label: 'Max Chunk Size', env: 'CHUNKS_MAX' },
  chunksSize: { section: 'chunks', label: 'Chunk Size', env: 'CHUNKS_SIZE' },
  coreDefaultDomain: { section: 'core', label: 'Default Domain', env: 'CORE_DEFAULT_DOMAIN' },
  coreReturnHttpsUrls: { section: 'core', label: 'Return HTTPS URLs', env: 'CORE_RETURN_HTTPS_URLS' },
  coreTempDirectory: { section: 'core', label: 'Temporary Directory', env: 'CORE_TEMP_DIRECTORY' },
  coreTrustProxy: { section: 'core', label: 'Trust Proxies', env: 'CORE_TRUST_PROXY' },
  discordAvatarUrl: { section: 'discord', label: 'Avatar URL', env: 'DISCORD_AVATAR_URL' },
  discordOnShortenAvatarUrl: {
    section: 'discord',
    label: 'Avatar URL',
    env: 'DISCORD_ON_SHORTEN_AVATAR_URL',
  },
  discordOnShortenContent: { section: 'discord', label: 'Content', env: 'DISCORD_ON_SHORTEN_CONTENT' },
  discordOnShortenEmbed: { section: 'discord', label: 'Embed', env: 'DISCORD_ON_SHORTEN_EMBED' },
  discordOnShortenUsername: { section: 'discord', label: 'Username', env: 'DISCORD_ON_SHORTEN_USERNAME' },
  discordOnShortenWebhookUrl: {
    section: 'discord',
    label: 'Webhook URL',
    env: 'DISCORD_ON_SHORTEN_WEBHOOK_URL',
  },
  discordOnUploadAvatarUrl: { section: 'discord', label: 'Avatar URL', env: 'DISCORD_ON_UPLOAD_AVATAR_URL' },
  discordOnUploadContent: { section: 'discord', label: 'Content', env: 'DISCORD_ON_UPLOAD_CONTENT' },
  discordOnUploadEmbed: { section: 'discord', label: 'Embed', env: 'DISCORD_ON_UPLOAD_EMBED' },
  discordOnUploadUsername: { section: 'discord', label: 'Username', env: 'DISCORD_ON_UPLOAD_USERNAME' },
  discordOnUploadWebhookUrl: {
    section: 'discord',
    label: 'Webhook URL',
    env: 'DISCORD_ON_UPLOAD_WEBHOOK_URL',
  },
  discordUsername: { section: 'discord', label: 'Username', env: 'DISCORD_USERNAME' },
  discordWebhookUrl: { section: 'discord', label: 'Webhook URL', env: 'DISCORD_WEBHOOK_URL' },
  domains: { section: 'domains', label: 'Domains', env: 'DOMAINS' },
  featuresDeleteOnMaxViews: {
    section: 'features',
    label: 'Delete on Max Views',
    env: 'FEATURES_DELETE_ON_MAX_VIEWS',
  },
  featuresHealthcheck: { section: 'features', label: 'Healthcheck', env: 'FEATURES_HEALTHCHECK' },
  featuresImageCompression: {
    section: 'features',
    label: 'Image Compression',
    env: 'FEATURES_IMAGE_COMPRESSION',
  },
  featuresMetricsAdminOnly: {
    section: 'features',
    label: 'Admin Only Metrics',
    env: 'FEATURES_METRICS_ADMIN_ONLY',
  },
  featuresMetricsEnabled: { section: 'features', label: 'Enable Metrics', env: 'FEATURES_METRICS_ENABLED' },
  featuresMetricsShowUserSpecific: {
    section: 'features',
    label: 'Show User Specific Metrics',
    env: 'FEATURES_METRICS_SHOW_USER_SPECIFIC',
  },
  featuresOauthRegistration: {
    section: 'features',
    label: 'OAuth Registration',
    env: 'FEATURES_OAUTH_REGISTRATION',
  },
  featuresRobotsTxt: { section: 'features', label: '/robots.txt', env: 'FEATURES_ROBOTS_TXT' },
  featuresThumbnailsEnabled: {
    section: 'features',
    label: 'Enable Thumbnails',
    env: 'FEATURES_THUMBNAILS_ENABLED',
  },
  featuresThumbnailsFormat: {
    section: 'features',
    label: 'Thumbnails Format',
    env: 'FEATURES_THUMBNAILS_FORMAT',
  },
  featuresThumbnailsInstantaneous: {
    section: 'features',
    label: 'Instantaneous Thumbnails',
    env: 'FEATURES_THUMBNAILS_INSTANTANEOUS',
  },
  featuresThumbnailsNumberThreads: {
    section: 'features',
    label: 'Thumbnails Number Threads',
    env: 'FEATURES_THUMBNAILS_NUM_THREADS',
  },
  featuresUserRegistration: {
    section: 'features',
    label: 'User Registration',
    env: 'FEATURES_USER_REGISTRATION',
  },
  featuresVersionChecking: {
    section: 'features',
    label: 'Version Checking',
    env: 'FEATURES_VERSION_CHECKING',
  },
  filesAssumeMimetypes: { section: 'files', label: 'Assume Mimetypes', env: 'FILES_ASSUME_MIMETYPES' },
  filesDefaultCompressionFormat: {
    section: 'files',
    label: 'Default Compression Format',
    env: 'FILES_DEFAULT_COMPRESSION_FORMAT',
  },
  filesDefaultDateFormat: {
    section: 'files',
    label: 'Default Date Format',
    env: 'FILES_DEFAULT_DATE_FORMAT',
  },
  filesDefaultExpiration: { section: 'files', label: 'Default Expiration', env: 'FILES_DEFAULT_EXPIRATION' },
  filesDefaultFormat: { section: 'files', label: 'Default Format', env: 'FILES_DEFAULT_FORMAT' },
  filesDisabledExtensions: {
    section: 'files',
    label: 'Disabled Extensions',
    env: 'FILES_DISABLED_EXTENSIONS',
  },
  filesDisabledTypes: { section: 'files', label: 'Disabled Types', env: 'FILES_DISABLED_TYPES' },
  filesDisabledTypesDefault: {
    section: 'files',
    label: 'Default MIME for Disabled Types',
    env: 'FILES_DISABLED_TYPES_DEFAULT',
  },
  filesExtensionlessUrls: { section: 'files', label: 'Extensionless URLs', env: 'FILES_EXTENSIONLESS_URLS' },
  filesLength: { section: 'files', label: 'Length', env: 'FILES_LENGTH' },
  filesMaxFileSize: { section: 'files', label: 'Max File Size', env: 'FILES_MAX_FILE_SIZE' },
  filesMaxFilesPerUpload: {
    section: 'files',
    label: 'Max Files Per Upload',
    env: 'FILES_MAX_FILES_PER_UPLOAD',
  },
  filesRandomWordsNumAdjectives: {
    section: 'files',
    label: 'Random Words Num Adjectives',
    env: 'FILES_RANDOM_WORDS_NUM_ADJECTIVES',
  },
  filesRandomWordsSeparator: {
    section: 'files',
    label: 'Random Words Separator',
    env: 'FILES_RANDOM_WORDS_SEPARATOR',
  },
  filesRemoveGpsMetadata: {
    section: 'files',
    label: 'Remove GPS Metadata',
    env: 'FILES_REMOVE_GPS_METADATA',
  },
  filesRoute: { section: 'files', label: 'Route', env: 'FILES_ROUTE' },
  httpWebhookOnShorten: { section: 'httpWebhook', label: 'On Shorten', env: 'HTTP_WEBHOOK_ON_SHORTEN' },
  httpWebhookOnUpload: { section: 'httpWebhook', label: 'On Upload', env: 'HTTP_WEBHOOK_ON_UPLOAD' },
  invitesEnabled: { section: 'invites', label: 'Enable Invites', env: 'INVITES_ENABLED' },
  invitesLength: { section: 'invites', label: 'Length', env: 'INVITES_LENGTH' },
  mfaPasskeysEnabled: { section: 'mfa', label: 'Passkeys', env: 'MFA_PASSKEYS_ENABLED' },
  mfaPasskeysOrigin: { section: 'mfa', label: 'Origin', env: 'MFA_PASSKEYS_ORIGIN' },
  mfaPasskeysRpID: { section: 'mfa', label: 'Relying Party ID', env: 'MFA_PASSKEYS_RP_ID' },
  mfaTotpEnabled: { section: 'mfa', label: 'Enable TOTP', env: 'MFA_TOTP_ENABLED' },
  mfaTotpIssuer: { section: 'mfa', label: 'Issuer', env: 'MFA_TOTP_ISSUER' },
  oauthBypassLocalLogin: { section: 'oauth', label: 'Bypass Local Login', env: 'OAUTH_BYPASS_LOCAL_LOGIN' },
  oauthDiscordAllowedIds: {
    section: 'oauth',
    label: 'Discord Allowed IDs',
    env: 'OAUTH_DISCORD_ALLOWED_IDS',
  },
  oauthDiscordClientId: { section: 'oauth', label: 'Discord Client ID', env: 'OAUTH_DISCORD_CLIENT_ID' },
  oauthDiscordClientSecret: {
    section: 'oauth',
    label: 'Discord Client Secret',
    env: 'OAUTH_DISCORD_CLIENT_SECRET',
  },
  oauthDiscordDeniedIds: { section: 'oauth', label: 'Discord Denied IDs', env: 'OAUTH_DISCORD_DENIED_IDS' },
  oauthDiscordRedirectUri: {
    section: 'oauth',
    label: 'Discord Redirect URL',
    env: 'OAUTH_DISCORD_REDIRECT_URI',
  },
  oauthGithubClientId: { section: 'oauth', label: 'GitHub Client ID', env: 'OAUTH_GITHUB_CLIENT_ID' },
  oauthGithubClientSecret: {
    section: 'oauth',
    label: 'GitHub Client Secret',
    env: 'OAUTH_GITHUB_CLIENT_SECRET',
  },
  oauthGithubRedirectUri: {
    section: 'oauth',
    label: 'GitHub Redirect URL',
    env: 'OAUTH_GITHUB_REDIRECT_URI',
  },
  oauthGoogleClientId: { section: 'oauth', label: 'Google Client ID', env: 'OAUTH_GOOGLE_CLIENT_ID' },
  oauthGoogleClientSecret: {
    section: 'oauth',
    label: 'Google Client Secret',
    env: 'OAUTH_GOOGLE_CLIENT_SECRET',
  },
  oauthGoogleRedirectUri: {
    section: 'oauth',
    label: 'Google Redirect URL',
    env: 'OAUTH_GOOGLE_REDIRECT_URI',
  },
  oauthLoginOnly: { section: 'oauth', label: 'Login Only', env: 'OAUTH_LOGIN_ONLY' },
  oauthOidcAuthorizeUrl: { section: 'oauth', label: 'OIDC Authorize URL', env: 'OAUTH_OIDC_AUTHORIZE_URL' },
  oauthOidcClientId: { section: 'oauth', label: 'OIDC Client ID', env: 'OAUTH_OIDC_CLIENT_ID' },
  oauthOidcClientSecret: { section: 'oauth', label: 'OIDC Client Secret', env: 'OAUTH_OIDC_CLIENT_SECRET' },
  oauthOidcRedirectUri: { section: 'oauth', label: 'OIDC Redirect URL', env: 'OAUTH_OIDC_REDIRECT_URI' },
  oauthOidcTokenUrl: { section: 'oauth', label: 'OIDC Token URL', env: 'OAUTH_OIDC_TOKEN_URL' },
  oauthOidcUserinfoUrl: { section: 'oauth', label: 'OIDC Userinfo URL', env: 'OAUTH_OIDC_USERINFO_URL' },
  pwaBackgroundColor: { section: 'pwa', label: 'Background Color', env: 'PWA_BACKGROUND_COLOR' },
  pwaDescription: { section: 'pwa', label: 'Description', env: 'PWA_DESCRIPTION' },
  pwaEnabled: { section: 'pwa', label: 'PWA Enabled', env: 'PWA_ENABLED' },
  pwaShortName: { section: 'pwa', label: 'Short Name', env: 'PWA_SHORT_NAME' },
  pwaThemeColor: { section: 'pwa', label: 'Theme Color', env: 'PWA_THEME_COLOR' },
  pwaTitle: { section: 'pwa', label: 'Title', env: 'PWA_TITLE' },
  ratelimitAdminBypass: { section: 'ratelimit', label: 'Admin Bypass', env: 'RATELIMIT_ADMIN_BYPASS' },
  ratelimitAllowList: { section: 'ratelimit', label: 'Allow List', env: 'RATELIMIT_ALLOW_LIST' },
  ratelimitEnabled: { section: 'ratelimit', label: 'Enable Ratelimit', env: 'RATELIMIT_ENABLED' },
  ratelimitMax: { section: 'ratelimit', label: 'Max Requests', env: 'RATELIMIT_MAX' },
  ratelimitWindow: { section: 'ratelimit', label: 'Window', env: 'RATELIMIT_WINDOW' },
  tasksCleanThumbnailsInterval: {
    section: 'tasks',
    label: 'Clean Thumbnails Interval',
    env: 'TASKS_CLEAN_THUMBNAILS_INTERVAL',
  },
  tasksClearInvitesInterval: {
    section: 'tasks',
    label: 'Clear Invites Interval',
    env: 'TASKS_CLEAR_INVITES_INTERVAL',
  },
  tasksDeleteInterval: { section: 'tasks', label: 'Delete Files Interval', env: 'TASKS_DELETE_INTERVAL' },
  tasksMaxViewsInterval: { section: 'tasks', label: 'Max Views Interval', env: 'TASKS_MAX_VIEWS_INTERVAL' },
  tasksMetricsInterval: { section: 'tasks', label: 'Metrics Interval', env: 'TASKS_METRICS_INTERVAL' },
  tasksThumbnailsInterval: {
    section: 'tasks',
    label: 'Thumbnails Interval',
    env: 'TASKS_THUMBNAILS_INTERVAL',
  },
  urlsLength: { section: 'urls', label: 'Length', env: 'URLS_LENGTH' },
  urlsRoute: { section: 'urls', label: 'Route', env: 'URLS_ROUTE' },
  websiteDefaultAvatar: { section: 'website', label: 'Default Avatar', env: 'WEBSITE_DEFAULT_AVATAR' },
  websiteExternalLinks: { section: 'website', label: 'External Links', env: 'WEBSITE_EXTERNAL_LINKS' },
  websiteLoginBackground: { section: 'website', label: 'Login Background', env: 'WEBSITE_LOGIN_BACKGROUND' },
  websiteLoginBackgroundBlur: {
    section: 'website',
    label: 'Login Background Blur',
    env: 'WEBSITE_LOGIN_BACKGROUND_BLUR',
  },
  websiteThemeDark: { section: 'website', label: 'Dark Theme', env: 'WEBSITE_THEME_DARK' },
  websiteThemeDefault: { section: 'website', label: 'Default Theme', env: 'WEBSITE_THEME_DEFAULT' },
  websiteThemeLight: { section: 'website', label: 'Light Theme', env: 'WEBSITE_THEME_LIGHT' },
  websiteTitle: { section: 'website', label: 'Title', env: 'WEBSITE_TITLE' },
  websiteTitleLogo: { section: 'website', label: 'Title Logo', env: 'WEBSITE_TITLE_LOGO' },
  websiteTos: { section: 'website', label: 'Terms of Service', env: 'WEBSITE_TOS' },
};
